{include file='before_body.phtml'}
<body class='contrast-fb without-footer'>
  {include file='header.phtml'}
  <div id='wrapper'>
    {include file='sidebar.phtml'}
    <section id='content'>
      <div class='container'>
        <div class='row' id='content-wrapper'>
          <div class='col-xs-12'>
            <div class='page-header page-header-with-buttons'>
              <h1 class='pull-left'>
                <i class='icon-tags'></i>
                <span>接口设置</span>
              </h1>
            </div>
            <div class='row'>
              <div class='col-sm-12'>
                <table class="data-table-column-filter table table-bordered table-striped dataTable" style="margin-bottom:0;" id="DataTables_Table_1" aria-describedby="DataTables_Table_1_info">
                  <thead>
                    <tr>
                      <th style="width:100px;">接口名</th>
                      <th style="width:90px;">类型1</th>
                      <th style="width:90px;">方式</th>
                      <th style="width:180px;">类型2</th>
                      <th style="width:90px;">发包口</th>
                      <th style="width:180px;">IP</th>
                      <td style="width:90px;">操作</td>
                    </tr>
                  </thead>
                  <tbody>
                    {foreach $result as $value}
                    <tr>
                      <td>{$value['name']}</td>
                      <td>{$value['type']|default: ''}</td>
                      <td>{$value['style']|default: ''}</td>
                      <td>{$value['type2']|default: ''}</td>
                      <td>{$value['outport']|default: ''}</td>
                      <td>{$value['ip']|default: ''}</td>
                      <td>
                        <a class="btn btn-success btn-xs" href="#ethEdit1" onclick="getData('{$value['name']}')" data-toggle="modal">编辑</a>
                      </td>
                    </tr>
                    {/foreach}
                  </tbody>
                </table>
              </div>
            </div>
            <!--弹出编辑框-->
            <div class="modal fade" id="ethEdit1" tabindex="-1" aria-hidden="true" style="display: none;">


            </div>

          </div>
        </div>
        {include file='footer.phtml'}
      </div>
    </section>
  </div>
</body>
{include file='after_body.phtml'}
<script type="text/javascript">
function getData(value) {
  var url = "{url('interface/getInterfaceByName?name=')}" + value;
  $('#ethEdit1').load(url);
}
getData('eth1');

function valid() {
  var ip = document.getElementById('ip').value;
  var mask = document.getElementById('mask').value;
  var gateway = document.getElementById('gateway').value;
  var dns1 = document.getElementById('dns1').value;
  var dns2 = document.getElementById('dns2').value;
  if(check(ip) && check(mask) && check(gateway) && check(dns1) && check(dns2)){
    document.getElementById('manage').submit();
  }else{
    alert('输入的数据格式错误，请重新输入！');
  }
}

function check(temp) {
  var reSpaceCheck = /^(\d+)\.(\d+)\.(\d+)\.(\d+)$/;
  if (reSpaceCheck.test(temp)){
    temp.match(reSpaceCheck);
    if (RegExp.$1<=255&&RegExp.$1>=0
      &&RegExp.$2<=255&&RegExp.$2>=0
      &&RegExp.$3<=255&&RegExp.$3>=0
      &&RegExp.$4<=255&&RegExp.$4>=0){
      return true;
  }else{
    return false;
  }
}else{
  return false;
}
}
</script>
</html>
